export default [
  { exact: true, path: '/', component: '@/pages/index' },
  { path: '/login', component: '@/pages/login/index', layout: false },
  {
    path: '/',
    component: '@/layouts/index',
    name: '仪表盘',
    icon: 'crown',
    access: 'isAdmin',
    routes: [
      {
        exact: true,
        path: '/user',
        name: '用户列表',
        access: 'canAccess',
        component: '@/pages/user/index',
      },
      {
        exact: true,
        path: '/services',
        name: '服务列表',
        access: 'canAccess',
        component: '@/pages/services/index',
      },
      {
        exact: true,
        path: '/products',
        name: '产品列表',
        access: 'canAccess',
        component: '@/pages/products/index',
      },
      {
        exact: true,
        path: '/cloud',
        name: '云平台',
        access: 'canAccess',
        component: '@/pages/cloud/index',
      },
      {
        exact: true,
        path: '/lifecycle',
        name: '组建生命周期',
        access: 'canAccess',
        component: '@/pages/lifecycle/index',
      },
      {
        exact: true,
        path: '/parentchild',
        name: '父组通信',
        access: 'canAccess',
        component: '@/pages/parentChild/index',
      },
      {
        exact: true,
        path: '/effecthook',
        name: '副作用测试',
        access: 'canAccess',
        component: '@/pages/effecthook/index',
      },
    ],
  },
];
